{"name": "test_call_api_with_error_status_codes[401-API调用失败：401 Client Error]", "status": "passed", "description": "测试各种HTTP错误状态码", "parameters": [{"name": "status_code", "value": "401"}, {"name": "expected_exception_msg", "value": "'API调用失败：401 Client Error'"}], "start": 1761614695523, "stop": 1761614695526, "uuid": "536fe7a3-d9c6-4f48-bea4-1f7d3b7c3c8a", "historyId": "063914a502201625729a2d4033849cdf", "testCaseId": "0ba28f683659835500083ccde95cdb5e", "fullName": "testcases.test_error_response.TestCallApi#test_call_api_with_error_status_codes", "labels": [{"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_error_response"}, {"name": "subSuite", "value": "TestCallApi"}, {"name": "host", "value": "DESKTOP-SQEMBVG"}, {"name": "thread", "value": "15580-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_error_response"}]}